---
name: Codespell

on:
  push:
    branches: [refuse-master]
  pull_request:
    branches: [refuse-master]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v1
